version: '3.8'

services:
    server:
        container_name: server
        image: server:1.0.0
        build:
            context: ./server/
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 5000:5000
        networks:
            - server-network
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

networks:
    server-network: