version: '3.9'

services:
    server:
        container_name: server
        image: server:1.0.0
        build:
            context: ./server/
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 5000:5000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - db
        links:
            - "db:database"
    db:
        container_name: db
        image: postgres:14-bullseye
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testdb
            POSTGRES_USER: postgres
        ports:
            - 5432:5432