version: '3.9'

services:
    server:
        container_name: server
        image: server:1.0.0
        build:
            context: ./server/
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 5000:5000
        volumes:
            - ./server:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on:
            - db
            - storage
        links:
            - "db:database"
    storage:
        container_name: storage
        image: minio/minio:latest
        ports:
          - "9000:9000"
          - "9001:9001"
        volumes:
          - ./storage/minio:/data
        environment:
          MINIO_ROOT_USER: ${MINIO_ROOT_USER}
          MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        command: server --address 0.0.0.0:9000 /data --console-address ":9001"
    createbuckets:
      image: minio/mc
      depends_on:
        - storage
      entrypoint: >
        /bin/sh -c "
        /usr/bin/mc alias set local http://storage:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD;
        /usr/bin/mc mb local/$MINIO_BUCKET_NAME;
        exit 0;
        "
    db:
        container_name: db
        image: postgres:14-bullseye
        restart: always
        environment:
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testdb
            POSTGRES_USER: postgres
        ports:
            - 5432:5432